### ISSUE TITLE
load N samples in memory (queue) and train on it on GPU. In the meanwhile, load another N samples into queue

### ISSUE THREAD

**Issue by shawnthu** [szymonmaszke/torchdata#22]
Hi, question as title.
What shall I do use torchdata?

**Comment by shawnthu** [comment]
Cuz the data loader is much slower than GPU consume, and the size of dataset on disk (e.g. IMAGES) is much bigger than memory size, So I have not way but to load part data in memory. BTW, pytorch data-loader does not meet the demand cuz each worker prepare a batch

**Comment by szymonmaszke** [comment]
See [this PR](https://github.com/szymonmaszke/torchdata/pull/17) which is released in `torchdata-nightly`.

It allows you to specify shared RAM cache for your data (example [here](https://github.com/szymonmaszke/torchdata/pull/17#issuecomment-740543697)). It is the only way (combined with partial caching, see documentation) to make it faster for `torch.utils.data.DataLoader` to load data faster (from memory instead of from disk).
